name: database
description: Database administration and queries

tools:
  - workflow_core    # Core workflow (session, persona, skill, memory)
  - mysql            # MySQL operations
  - postgres         # PostgreSQL operations
  - sqlite           # SQLite operations
  - ssh              # Remote database access

# Note: This persona is focused on database operations.
# For infrastructure tasks, switch to infra persona.

skills:
  # Database operations
  - debug_prod              # Debug production database issues
  - check_secrets           # Verify database credentials
