# Project Persona Configuration
# Focused on project/repo context management and knowledge

name: project
description: Project context, knowledge management, and repo navigation
persona: personas/project.md

# Tool modules to load (from tool_modules/aa_*)
# Using _core suffix for heavy modules to stay under 80 tool limit
tools:
  - workflow_core   # 18 tools - Core (session, persona, skill, memory)
  - git_core        # 8 tools - Git operations for repo navigation
  - code_search     # 9 tools - Semantic code search
  - knowledge       # 6 tools - Project knowledge management
  - project         # 5 tools - Project configuration

# Total: ~46 tools

# Note: Use tool_exec() for tools from other modules if needed

skills:
  # Project management
  - memory_view         # View/manage persistent memory
  - learn_pattern       # Save learned pattern

  # Code navigation
  - start_work          # Start working on an issue (sets project context)
