# Project Persona Configuration
# Focused on project/repo context management and knowledge

# Auto-validated: 2026-02-06
# Use tool_list() to discover available tools

name: project
description: Project context, knowledge management, and repo navigation
persona: personas/project.md

# Tool modules to load (from tool_modules/aa_*)
# Using _core suffix for heavy modules to stay under 80 tool limit
tools:
  - workflow_core   # Core (session, persona, skill, memory)
  - git_core        # Git operations for repo navigation
  - code_search     # Semantic code search
  - knowledge       # Project knowledge management
  - project         # Project configuration

# Note: Use tool_exec() for tools from other modules if needed

skills:
  # Project management
  - memory_view         # View/manage persistent memory
  - learn_pattern       # Save learned pattern

  # Code navigation
  - start_work          # Start working on an issue (sets project context)
